version: '3'
services:
    aczd:
        image: apergudev/sompo:latest
        container_name: sompo
        restart: always
        ports:
            - "9004:9004"
        environment:
            APP_NAME: sompo
            DB_CONNECTION: mysql
            DB_HOST: 127.0.0.1
            DB_PORT: 3306
            DB_DATABASE: sompo
            DB_USERNAME: root
            DB_PASSWORD: secret
            BASIC_AUTH_USERNAME: pR1vY
            BASIC_AUTH_PASSWORD: pa55w0rd@pR1vY
