version: '3'
services:
    aczd:
        image: apergudev/sompo:latest
        container_name: sompo
        restart: always
        ports:
            - "9004:9004"
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_DATABASE: sompo_cust
            DB_USERNAME: root
            DB_PASSWORD:
            BASIC_AUTH_USERNAME: pR1vY
            BASIC_AUTH_PASSWORD: pa55w0rd@pR1vY
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: sompo_cust
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
